name: Docker Compose build (Release)
on:
  release:
    types: [ published ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the images
        run: DISCOURSE_DOCKER_VERSION=${GITHUB_REF##*/} docker-compose build
      - uses: azure/docker-login@v1
        with:
          login-server: index.docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push the images to Docker Hub
        run: DISCOURSE_DOCKER_VERSION=${GITHUB_REF##*/} docker-compose push
      - name: Tag latest
        run: DISCOURSE_DOCKER_VERSION=latest docker-compose push        